### ISSUE TITLE
The fucking gallery codes

### ISSUE THREAD

**Issue by sharmayu** [vg-mjg/mjg-repo#10]
I'm going to fix the fucking broken-ass jumbled mess of a gallery code if it's the last thing I do.

**Comment by sharmayu** [comment]
Still needs a redesign, something easier to update and doesn't load every single page at first open.

**Comment by Furitenman** [comment]
This was on my list too. Put it at the bottom to leave more time to think about it. Any ideas/examples as to how you want it to look like?

**Comment by sharmayu** [comment]
It really doesn't matter as long as it's now how it is right now, and it's faster to update pages

**Comment by Furitenman** [comment]
I've done some rework on the one shot pages, it's a draft. It would basically just be one page for all comics loaded through javascript. It should save us a lot of unnecessary htmls. I would use a similar template for the galleries. Let me know what you think.

**Comment by sharmayu** [comment]
It's too zoomed in, is there are way to set the pages to a 600-800px limit?

**Comment by Furitenman** [comment]
I’ll see if I can fix that.

**Comment by Furitenman** [comment]
I'm still working on this. Just some small roadblocks.

**Comment by watterle** [comment]
Something using https://getbootstrap.com/docs/4.0/components/carousel/#with-indicators ?
haha where are the drawfags.....

**Comment by Furitenman** [comment]
I mean, yeah. I just have some problem integrating comics that are chaptered. Also a fight with different sizes that's not fun.
