### ISSUE TITLE
Test Torrent

### ISSUE THREAD

**Issue by sharmayu** [vg-mjg/mjg-repo#105]
Someone make a torrent of all the games at the [repo offline game downloads](https://repo.riichi.moe/library.html#resources-offline). I can't do it myself because I don't have the speed or storage for it.

Also take note that [this game](https://sukebei.nyaa.si/view/3213231) is not in the mega backups [1](https://mega.nz/folder/ZtkHHKzQ#iDCGRuVitS1aFF85mvIZAQ) or [2](https://mega.nz/folder/8Yp3HCyK#gOQ2pRX4LewS2jA-8Z81hw).

**Comment by watterle** [comment]
shan't

**Comment by sharmayu** [comment]
okay we'll just go with the current system we have hoping it doesn't disappear one day... but i'll wait for like 3 days maybe someone will do it...

**Comment by Furitenman** [comment]
Won't be me.

**Comment by sharmayu** [comment]
the torrent dream... is dead...

**Comment by sharmayu** [comment]
how could this be........ we were supposed to make the torrent...... not leave it dying on the ground...
