### ISSUE TITLE
Link color

### ISSUE THREAD

**Issue by watterle** [vg-mjg/mjg-repo#107]
It's really hard to see if you're clicking a link when you're using light mode

**Comment by sharmayu** [comment]
holy fucking based

**Comment by Furitenman** [comment]
Then don't click it.

**Comment by Furitenman** [comment]
Give it a try now.

**Comment by watterle** [comment]
t-thanks
![1045 (2)](https://user-images.githubusercontent.com/49875739/121072765-e80a1800-c7d1-11eb-830c-c3a342607378.png)

**Comment by Furitenman** [comment]
Okay, now you'll like the change.
