### ISSUE TITLE
Delete shamiko from index.html

### ISSUE THREAD

**Issue by Furitenman** [vg-mjg/mjg-repo#108]
CoolDogz has decided that the repo needs cleaning. Delete the shamiko image at the bottom and replace it with gangsta Wanshiro: 
![wanjirou gangsta emote](https://user-images.githubusercontent.com/82289213/121042095-a4a0b100-c7b3-11eb-8b77-41c63084c058.png)

> B-But muh identity
>
Fuck you. Article IV section 4. It also doesn't break the article II section 1.
> Do it yourself
>
That wouldn't be enjoyable enough for us. We want repoanon to do it.

**Comment by sharmayu** [comment]
ahhhhh...... th-this can't be real..... how could the dogfuckers win.....

**Comment by Furitenman** [comment]
Holy based.

**Comment by sharmayu** [comment]
i will bring shamiko back, no matter what it takes... i will never forget this transgression...

**Comment by sharmayu** [comment]
![miyanagasaki-6](https://user-images.githubusercontent.com/67625878/121048872-c87ee980-c7e9-11eb-982f-d473e3e440a5.png)

**Comment by Furitenman** [comment]
Just win a tourney bro :^)
