### ISSUE TITLE
saki vita dumps

### ISSUE THREAD

**Issue by watterle** [vg-mjg/mjg-repo#109]
reminder to add them somewher

**Comment by sharmayu** [comment]
i'll do this tomorrow (or maybe someone will before me)

**Comment by Furitenman** [comment]
Maybe in media/others?

**Comment by sharmayu** [comment]
nah this is going to game resources > others section

And just before I forget, here are the links
[event cg, backgrounds and character image files](https://mega.nz/file/xQdUSDhY#YNnuy7yTMxrhbR9psBqz5UmsEPSae3UY0bou-l8HOzU)
[yaku voicelines](https://mega.nz/file/0B9CXTib#yjKhFXHfDnjz1mFUS_0F2g0GPMUYRieKEo1G8qOKp8s)

**Comment by Furitenman** [comment]
Done.

**Comment by sharmayu** [comment]
someone put this in the updates

**Comment by sharmayu** [comment]
my back hurts and it feels like i'm going to die but don't forget to put it in the updates!

**Comment by Furitenman** [comment]
Forgot about that part. I'm the codemonkey repoanon.
