### ISSUE TITLE
bitcoin miners

### ISSUE THREAD

**Issue by watterle** [vg-mjg/mjg-repo#113]
have our reddit and discord friends fund the servers

**Comment by watterle** [comment]
![1198](https://user-images.githubusercontent.com/49875739/126337192-6a20d86a-878f-4174-8d8e-c80c7c7c3c95.png)
lovely

**Comment by Furitenman** [comment]
![1612283808665](https://user-images.githubusercontent.com/82289213/126351577-c9bb6269-bde3-42ba-b03b-982719220771.jpg)
>Ze install da mod? MINE EET
