### ISSUE TITLE
Interactive Meido

### ISSUE THREAD

**Issue by sharmayu** [vg-mjg/mjg-repo#12]
Still in development. Interactive meido that will help you find what you want in the repo because anons are retarded and can't navigate through the site to save their lives, holy shit.

**Comment by watterle** [comment]
![smug](https://files.catbox.moe/l3c0ht.png "smug")

**Comment by watterle** [comment]
we have the technology now?

**Comment by sharmayu** [comment]
Always had, I already showed you a sample from the RB1 vn.

**Comment by watterle** [comment]
Grim

**Comment by Furitenman** [comment]
You can do it like Clipo and it may not be that much of a hassle to write, at least a simple version.

**Comment by sharmayu** [comment]
Found the code. It's gonna be full-featured with the whole package, along with rb1 vn. It's at the vn folder, and you can test the output I made a year ago [here](https://repo.riichi.moe/vn/index.html). Plans are at the Planning.txt at the same vn folder. I'll write up everything as soon as I find the time™.

**Comment by watterle** [comment]
>PROGRESS: [][ ][ ][ ][ ][ ][ ] 14.28%

better than expected
![ichihime-0](https://user-images.githubusercontent.com/49875739/117245867-db457d80-ae3b-11eb-8093-bba84e0497cd.png)

**Comment by Furitenman** [comment]
> 
> 
> Found the code. It's gonna be full-featured with the whole package, along with rb1 vn. It's at the vn folder, and you can test the output I made a year ago [here](https://repo.riichi.moe/vn/index.html). Plans are at the Planning.txt at the same vn folder. I'll write up everything as soon as I find the time™.

Wouldn't be better to put it in a separate repo? Well, not like this repo is the most organized thing ever.

**Comment by watterle** [comment]
>Wouldn't be better to put it in a separate repo? 

yes

**Comment by indronna** [comment]
I could probably help on the VN project as a dev if you want but since I didn't finish reading the rb1, don't expect me to be able to write any class

**Comment by sharmayu** [comment]
>Wouldn't be better to put it in a separate repo? 

Yes, but it's just there for backup. I'll make a separate repo for it.

>I didn't finish reading the rb1

Same.

**Comment by sharmayu** [comment]
> 
> 
> > PROGRESS: [][ ][ ][ ][ ][ ][ ] 14.28%
> 
> better than expected

The original files for that with a template lobby is lost, so no it's worse sorry.

**Comment by watterle** [comment]
am I the only one that read rb1.....?

**Comment by KioKenN** [comment]
English literature regarding mahjong is so sparse I'm surprised you haven't read the books multiple times already.

**Comment by Furitenman** [comment]
I put the vn in a separate branch in the repo. That way you can have less clutter for both the repo and the vn.

> 
> 
> am I the only one that read rb1.....?

I read it... but skimmed through some parts that did not interest me.

**Comment by sharmayu** [comment]
>separate branch

I don't know how to deal with separate branches...

**Comment by Furitenman** [comment]
> 
> 
> > separate branch
> 
> I don't know how to deal with separate branches...
https://www.nobledesktop.com/learn/git/git-branches

**Comment by sharmayu** [comment]
Okay thanks I finally got how to work it out.

**Comment by Furitenman** [comment]
VN doko

**Comment by sharmayu** [comment]
i'll seriously start on a vn next week...

**Comment by Furitenman** [comment]
I can help after the league ends. In fact, I feel like if I help I'll end up coding the whole thing myself...

**Comment by sharmayu** [comment]
now if we only had a working script haha...

**Comment by sharmayu** [comment]
i'm still not sure on what direction is the vn going to head. will it be story-heavy, or will it be pure "learning mahjong with your favorite maid?" a class format, or should there be a proper storyline? i will write a proposal in the weekend so we can start from there

**Comment by Furitenman** [comment]
Make a new repo for it, don't clutter this one. We can also draft ideas there and use it to make a recruitment in the thread. What I would do is divide the game in 2 parts:
1) VN with story (full game)
2) RB1 teachings (skips the story mode and focuses on the learning)
