### ISSUE TITLE
Missing tourney

### ISSUE THREAD

**Issue by KioKenN** [vg-mjg/mjg-repo#123]
/mjg/ vs may is missing

**Comment by KioKenN** [comment]
Will add eventually.

**Comment by watterle** [comment]
no it's in "others"

**Comment by watterle** [comment]
maybe it deserves its own spot? The plans are to make it a recurrent thing

**Comment by KioKenN** [comment]
I guess I am blind seems okay to me to put it in the others. If it becomes a regular thing yeah we should probably make it it's own thing.
