### ISSUE TITLE
Put an embedded calendar for events

### ISSUE THREAD

**Issue by sharmayu** [vg-mjg/mjg-repo#127]
Like something from [teamup](https://teamup.com/) because fuck using timezone conversions and shit. Fuck it.
\>wtf do it yourself
Yeah sure I'll do it myself when I get over my coof and retarded-ass research project, but maybe (You) might do it for me so I'm just gonna throw it here

**Comment by watterle** [comment]
wtf do it yourself

**Comment by sharmayu** [comment]
Yeah sure I'll do it myself when I get over my coof and retarded-ass research project, but maybe (You) might do it for me so I'm just gonna throw it here

**Comment by Furitenman** [comment]
Soon(tm)

**Comment by Furitenman** [comment]
We could use this: https://support.google.com/calendar/answer/41207?hl=en
Might be easier since most of us have a disposable gmail account.

**Comment by watterle** [comment]
I have a calendar, but where are you going to add it? I can add people that can change it and all of that, and you can customize most of the size/shape/whatever, just find a place for it. @Furitenman 

`<iframe src="https://calendar.google.com/calendar/embed?height=200&wkst=1&bgcolor=%23ffffff&ctz=UTC&showTitle=0&showDate=0&showNav=0&showPrint=0&showTabs=0&showCalendars=0&hl=en_GB&mode=AGENDA&src=cGVuZHJhZ29ucGVuZHJhZ29uNkBnbWFpbC5jb20&color=%23039BE5" style="border-width:0" width="800" height="200" frameborder="0" scrolling="no"></iframe>`
`<iframe src="https://calendar.google.com/calendar/embed?height=300&wkst=1&bgcolor=%23ffffff&ctz=UTC&showTitle=1&showDate=1&showNav=1&showPrint=0&showTabs=0&showCalendars=0&hl=en_GB&mode=MONTH&src=cGVuZHJhZ29ucGVuZHJhZ29uNkBnbWFpbC5jb20&color=%23039BE5" style="border-width:0" width="800" height="300" frameborder="0" scrolling="no"></iframe>`

**Comment by Furitenman** [comment]
Well, it's done. Looks acceptable.
