### ISSUE TITLE
daily wwyd

### ISSUE THREAD

**Issue by watterle** [vg-mjg/mjg-repo#129]
![1570](https://user-images.githubusercontent.com/49875739/138918187-39cab038-697a-4da2-aba6-5c0be60a615b.png)
you know you want it
you know nips have the superior site
shan't do it myself

**Comment by Furitenman** [comment]
Repo calendar doko? We need to make money now that everyone blocked the crypto miner

**Comment by watterle** [comment]
best 12 loli of the year? Sound like business

**Comment by Furitenman** [comment]
That and 12 pictures of eigamma

**Comment by Furitenman** [comment]
Was thinking about this last night. Generating it would be a pain in the ass, but it's not impossible. Easiest way would be to upload a bunch of wwyd into images and add them somwhere. Javascript is a bit limited about how to handle this, so I don't know if we can show everyone the exact same wwyd every day. Best I can do is:
* A bunch of random wwyd images from the book.
Or
* Use the tile font to generate it and hope it doesn't fuck up.

**Comment by watterle** [comment]
random wwyd from the books sounds good enough
