### ISSUE TITLE
yes

### ISSUE THREAD

**Issue by nikaidou-agate** [vg-mjg/mjg-repo#134]
there should be an option to replace the lolis with cute shotas. kinda like the day/night mode switch, but it gives you cute little penises instead of making the site look worse. also we could replace some of the rius with, preferably, cute soras or **bonded** ryans (unbonded is shit).

@cero54010960
@YostarGlobal
@rezalon
@BTypeHStyle
@Sweetrollarino
@ninomaeinanis

**Comment by watterle** [comment]
uhhhhhhhh that's gay
