### ISSUE TITLE
Tourneys

### ISSUE THREAD

**Issue by watterle** [vg-mjg/mjg-repo#137]
make up another category for single tourneys and leave "Other" to non-/mjg/ ones

**Comment by KioKenN** [comment]
Yeah the tourney page should be reorganised

**Comment by watterle** [comment]
\>@[KioKenN](https://github.com/KioKenN) KioKenN self-assigned this [on 10 Apr](https://github.com/vg-mjg/mjg-repo/issues/137#event-6404040143)

**Comment by chinponya** [comment]
meds

**Comment by watterle** [comment]
shan't

**Comment by KioKenN** [comment]
soon(tm)

**Comment by KioKenN** [comment]
9d6d084a5eba2cd1c04e09464e036aee4d1bc569 done
