### ISSUE TITLE
random wwyd pt2

### ISSUE THREAD

**Issue by watterle** [vg-mjg/mjg-repo#141]
https://boards.4channel.org/vg/thread/407399410#p407469981
@Furitenman @vg-mjg/repoanons

**Comment by Furitenman** [comment]
https://docs.google.com/spreadsheets/d/178CFLNJJ9aCNkkkFgfX_qeywnIcBICLfzJQHRN48ICk/edit#gid=0

**Comment by chinponya** [comment]
if you need tiles, you can use this svg bundle instead of bloated pngs, so it doesn't make trillion requests for no good reason https://files.catbox.moe/7hft5q.svg
you can then reference the tiles like so
```
<svg class="some-tile-class-so-it-actually-looks-like-a-tile" fill="">
    <use href="/images/tiles.svg#2p"></use>
</svg>
```

**Comment by chinponya** [comment]
some other implementations that got posted on >irc
https://user-images.githubusercontent.com/49875739/138918187-39cab038-697a-4da2-aba6-5c0be60a615b.png
https://www.maru-jan.com/content/nanikiru_god/
https://nnkr.jp/questions/result/19851
http://www.saki-anime.com/1st/nanikiru/Problems/resultview/5520

**Comment by watterle** [comment]
https://github.com/eric200203/mahgen
https://github.com/wangjiezhe/tenhou-img

**Comment by chinponya** [comment]
https://repo.riichi.moe/wwyd.html
I hope this is at least close to good enough.
I'm just not sure where it should even live.
