### ISSUE TITLE
Reorganization of the Repo Frontpage

### ISSUE THREAD

**Issue by sharmayu** [vg-mjg/mjg-repo#144]
I don't want to change the layout, I just want to make things more organized. Based on the questionnaire, here's what we can do:

![repo layout proposal](https://github.com/vg-mjg/mjg-repo/assets/67625878/c8cbc076-53f3-411a-b8a4-6c162a6192ad)

\>why don't you do it yourself
If you let me do it I WILL break the repo. No I will not fix it back. In fact, I will change the layout entirely just because the code's too convoluted for me. Fuck you faggots if you let me do this. 
\>but muh constitution
Then fix it.
\>but muh years of the repo layout being the same
Then fix it.
\>I will delete the repo if you do this
That's... good?

**Comment by chinponya** [comment]
how are you going to fit quicklinks in the top left when it's the largest section on the page

**Comment by sharmayu** [comment]
just lower the font and make it squeeze, trust the plan two more sizes down

**Comment by watterle** [comment]
retard

**Comment by sharmayu** [comment]
I think that means "Based" in /mjg/ speak so I'll go ahead and do it.

**Comment by NamaikiNaNeko** [comment]
Bring back the VN layout that lasted for like a day because it was so bad.
Now THAT had potential

**Comment by sharmayu** [comment]
> Bring back the VN layout that lasted for like a day because it was so bad. Now THAT had potential

No, I couldn't stand it the first time i saw it. But maybe going in that direction...

**Comment by sharmayu** [comment]
Ahh... i found it. I found a way to make things work without breaking the current layout. Holy shit i'm a fucking genyas.

**Comment by sharmayu** [comment]
and done. change anything and repo deleto.
