### ISSUE TITLE
Remove the big space

### ISSUE THREAD

**Issue by sharmayu** [vg-mjg/mjg-repo#146]
![brave_EsnwNueWz8](https://github.com/vg-mjg/mjg-repo/assets/67625878/6afdc969-d822-4144-86e8-db3ce812479b)

Whoever was in charge of this, please fix it. Or I will forcefully fix (break) it.

**Comment by chinponya** [comment]
it's sirl's fault but I fixed it

**Comment by sharmayu** [comment]
thanks
