### ISSUE TITLE
Replace catbox links with mega

### ISSUE THREAD

**Issue by sharmayu** [vg-mjg/mjg-repo#5]
Replace the catbox links which may or may not last to prevent future me from doing it when catbox goes down.

**Comment by watterle** [comment]
it's not like mega is updated either

**Comment by watterle** [comment]
more than not updated, it's completely dead

**Comment by watterle** [comment]
been like that for a while btw

**Comment by watterle** [comment]
ok it works now....?

**Comment by Furitenman** [comment]
Use google drive maybe?

**Comment by sharmayu** [comment]
uhhh i'll do this, i've got the account it's just that it's overfilled. It's easy to make a new account anyway for new things, but I'll add the mega links we have back.
![1607085626330](https://user-images.githubusercontent.com/67625878/118876935-69cbfb80-b920-11eb-8940-7f06f26aabb5.png)

**Comment by sharmayu** [comment]
Question: Is mega really the best place to archive everything? I remember reading that the links die if you don't go online on the account for a few months. Maybe we should make google drives, I've got lots of burner SIM cards I can buy for half a dollar.

**Comment by sharmayu** [comment]
ehhhh looks like google isn't nice since it's going to be hard to share accounts. so maybe multiple mega accounts?

Also researching [ipfs](https://ipfs.io/) to see if it's good, which [/hgg2d/ uses](https://ipfs.io/ipns/k2k4r8l7mxpi57sotykoy5f5ucakg0dr0ib0avmyjhwmofkvpfhfd510/bin.html).

**Comment by Furitenman** [comment]
Could also consider a torrent of all the /mjg/ content similar to what /g/ does with the tech books.

**Comment by sharmayu** [comment]
Who's going to seed it? Someone suggested a seedbox but I doubt we can afford it
