### ISSUE TITLE
W I D E banner not centered

### ISSUE THREAD

**Issue by sharmayu** [vg-mjg/mjg-repo#72]
![autism](https://files.catbox.moe/k6dh9v.png)
This is really bothering me. Can't this be centered? I'll even break the entire repo just to center this.

**Comment by Furitenman** [comment]
I'll give it a look, might have to make changes for this specific banner. Odd bug.

**Comment by Furitenman** [comment]
It's a tricky thing, since it overflows the current measurement of the column. I fixed it by widening the column. Does this work?
![](https://user-images.githubusercontent.com/82289213/117351135-a540e180-aead-11eb-8538-6fc9de49aa3a.png)

**Comment by sharmayu** [comment]
works perfectly like that
