### ISSUE TITLE
Free for all

### ISSUE THREAD

**Issue by watterle** [vg-mjg/mjg-repo#74]
you should all be members with writing rights. Have fun repoanons
![sheephah](https://user-images.githubusercontent.com/49875739/117375460-4b511380-aecf-11eb-8f60-88f358a4cd87.png)

**Comment by watterle** [comment]
not too much

**Comment by Furitenman** [comment]
Based. Time to flood the repo with ha(g)ts.

**Comment by KioKenN** [comment]
:)

**Comment by indronna** [comment]
I'm scared

**Comment by watterle** [comment]
>h*g

**Comment by sharmayu** [comment]
time to delete the repo and establish the wiki.

**Comment by watterle** [comment]
oh no
