### ISSUE TITLE
OCs and Tourneys Page Format Fix

### ISSUE THREAD

**Issue by sharmayu** [vg-mjg/mjg-repo#77]
Low priority, but it would be nice for the OCs and Tourneys page to have the same format as the Library page. But it's low priority because the pages themselves just werks. Tried to do it myself but it just won't cooperate.

**Comment by Furitenman** [comment]
OCs should **now** be working like the library. Gonna do the same with Tourneys tomorrow or sunday probably.

**Comment by sharmayu** [comment]
Wow that was fast, thanks.

**Comment by Furitenman** [comment]
Done. Shoul be working fine just now.
