### ISSUE TITLE
Maid blocking Library links

### ISSUE THREAD

**Issue by poyayaaan** [vg-mjg/mjg-repo#78]
The maid is blocking the links at the lowest part of some of the sections in the Library.

![1604163380755](https://user-images.githubusercontent.com/82838527/117538574-65a70080-b039-11eb-893e-5b189e118cf4.png)

**Comment by Furitenman** [comment]
Baka meido

**Comment by Furitenman** [comment]
Should be solved now, I tested it in a low resolution (1366 x 768) so I assume if it scales it will also do the trick.
