### ISSUE TITLE
Improve the updates section

### ISSUE THREAD

**Issue by Furitenman** [vg-mjg/mjg-repo#79]
This part is pretty much a bloat of code in the index.html page.
![](https://user-images.githubusercontent.com/82289213/117702545-ef390880-b1c8-11eb-83c2-c271b119e76b.png)

At the time I re-worked it, I left it as-is since it would be easier to get approval. I'm thinking of putting all the info in a simple .json file and calling it with javascript to make it a) easier to update and b) easier to work with the index.html. Thoughts?

**Comment by sharmayu** [comment]
Then we should also set a limit of entries in the updates section. Maybe 20?

**Comment by watterle** [comment]
It looks easy to update, so sure, please do it

**Comment by Furitenman** [comment]
I’ll upload it this afternoon then.
