### ISSUE TITLE
Updates broken

### ISSUE THREAD

**Issue by watterle** [vg-mjg/mjg-repo#81]
More space for loli I guess @Furitenman 
![879 (2)](https://user-images.githubusercontent.com/49875739/118014580-a82b4e80-b353-11eb-9f92-1634e221c818.png)

**Comment by Furitenman** [comment]
It was a lint error. Should be fixed now. My browser had the file cached so I couldn't see the error earlier.

**Comment by watterle** [comment]
now it works, thanks. Only a minor(?) thing tho, page needs 2 minutes to stop loading even if apparently everything is loaded. Is it just me?

**Comment by Furitenman** [comment]
Did you clear your cache? This page is kinda heavy on things. I can't somehow reproduce it, unless I use a private session. But taking stuff out of the index would make it soulless.

**Comment by watterle** [comment]
I think I got it. It's catbox that's shitting itself right now

**Comment by watterle** [comment]
h-haha not like 98% of the files are on catbox without a backup haha

**Comment by Furitenman** [comment]
I just realised but why are you using the light theme? Are you a psychopath?

**Comment by watterle** [comment]
I hate dark themes with much passion
