### ISSUE TITLE
Library fix

### ISSUE THREAD

**Issue by watterle** [vg-mjg/mjg-repo#82]
Low priority, but it would be nice for the Library page to be easier to maintain. 2000 lines of code in the same file are a bit too much

**Comment by Furitenman** [comment]
That might be an organization thing. Maybe we could break down the Library in different sub-pages?

**Comment by sharmayu** [comment]
Just be autistic enough
... or you can do it the same way you did the updates with separate json files, that works.

> Maybe we could break down the Library in different sub-pages?

The current tabs organization works, separating them in subpages feels wonky.

**Comment by Furitenman** [comment]
> Just be autistic enough

Guess I'll do that. Gimme a couple of days to figure something out.

**Comment by Furitenman** [comment]
Okay, so this is the solution I came up with. I divided the entire library in different html files, which are loaded into the library. This would have the following structure:
```
├───resources
│       resources-game.html
│       resources-gguides.html
│       resources-majplus.html
│       resources-media.html
│       resources-mjg.html
│       resources-mleague.html
│       resources-offline.html
│       resources-strategy.html
│       resources-toolz.html
```
Tell me what you guys think and I'll push it to master.

**Comment by sharmayu** [comment]
We won't know until we actually see it in action, so push and we'll feel if it's good or not.

**Comment by watterle** [comment]
looks good tbh

**Comment by Furitenman** [comment]
It's up. Test it and tell me what you guys think.

**Comment by watterle** [comment]
Really nice. The only problem is that if you open the page coming from the light theme, you get a wierd mix of light and dark themes

**Comment by Furitenman** [comment]
Yeah, good catch. Should be fix in the next push.

**Comment by watterle** [comment]
nice
