### ISSUE TITLE
Tourney/OC pages

### ISSUE THREAD

**Issue by watterle** [vg-mjg/mjg-repo#83]
Nothing but the navbar is loaded if coming from the homepage. After clicking on the navbar it works tho
![898](https://user-images.githubusercontent.com/49875739/118254068-f7d05e00-b4aa-11eb-98e9-74a47f7f81ce.png)
![900](https://user-images.githubusercontent.com/49875739/118254071-f868f480-b4aa-11eb-8308-bfb8aaf84ce3.png)

**Comment by Furitenman** [comment]
I'll check it out.

**Comment by Furitenman** [comment]
It should work now.

**Comment by watterle** [comment]
it does
