### ISSUE TITLE
Cramped News and Updates

### ISSUE THREAD

**Issue by sharmayu** [vg-mjg/mjg-repo#86]
Is it just me or does the News and Updates section feel too cramped? Close this topic if you think it's just my autism acting up.

**Comment by sharmayu** [comment]
![reorganization proposal](https://user-images.githubusercontent.com/67625878/118386978-f8552a00-b64d-11eb-8092-9e89ed7b03c2.png)
Here's a new layout proposal, with the news and updates being a sidebar taking maybe 30% of the horizontal space.
Fuck symmetryfags.

**Comment by watterle** [comment]
noooooooooooooooooooooooooooo the symmetry

**Comment by Furitenman** [comment]
It's not a bad idea, but I feel it's a bit too much space for updates. I would move the updates a row down and maybe add tourney stats on the repo? I don't know how much info the api can give us at the moment. It would look nice.

**Comment by sharmayu** [comment]
I want the updates to be one of the first things you see when you open the repo, so maybe the tourney stats can be below the updates. But I don't know about the tourney stats and how to implement that. I'll try testing the layouts to see if it works or not, then I'll push it then we can decide to keep it or not.

> noooooooooooooooooooooooooooo the symmetry

I will never forgive symmetryfags for rejecting the best version of the repo, the one with the cool sidebar at the right

**Comment by Furitenman** [comment]
I see your point. It's not hard to move it, just follow the grids. If you're unsure how it works, check this: https://getbootstrap.com/docs/4.6/layout/grid/ and you'll be able to accomodate. I think adding the tournament stuff could be possible, I should ask the API guys.

**Comment by sharmayu** [comment]
Okay thanks, i'll follow this since it looks easier to use than the usual bullshit i do

**Comment by sharmayu** [comment]
Wow it's so fucking complicated I'll bother with this next time...

**Comment by Furitenman** [comment]
What's complicating you?

**Comment by watterle** [comment]
![suzumiyaanju-4](https://user-images.githubusercontent.com/49875739/118406433-61539680-b67c-11eb-8069-fa05aefbefca.png)

**Comment by Furitenman** [comment]
You want something like this @sharmayu? >inb4 we get complains for changing the layout again
![Screenshot_2021-05-16  mjg Repository](https://user-images.githubusercontent.com/82289213/118408134-5e5ca400-b684-11eb-9404-923553874710.png)

**Comment by watterle** [comment]
changing layout every week is peak repo schizodev, pure soul

**Comment by sharmayu** [comment]
Yeah like that, it works. Pls push

**Comment by watterle** [comment]
when did you start getting scared of breaking the repo?

**Comment by sharmayu** [comment]
to my defense i've always worked with basic html/css/java, so i know how to move things around even when everything breaks. maybe i'll experiment with bootstrap but it hates offline shit

**Comment by sharmayu** [comment]
> You want something like this @sharmayu? >inb4 we get complains for changing the layout again
> ![Screenshot_2021-05-16 mjg Repository](https://user-images.githubusercontent.com/82289213/118408134-5e5ca400-b684-11eb-9404-923553874710.png)

Where's the push...?

**Comment by Furitenman** [comment]
I’m at work. In an hour or so I’ll upload it.

**Comment by Furitenman** [comment]
Pushed
> 
> 
> to my defense i've always worked with basic html/css/java, so i know how to move things around even when everything breaks. maybe i'll experiment with bootstrap but it hates offline shit
Once you get the hang of it, you can do a lot of stuff in just a couple of lines of code instead of having to fight with thousands of lines of css/javascript.

**Comment by sharmayu** [comment]
>instead of having to fight with thousands of lines of css/javascript.

But that's the fun in it...

**Comment by sharmayu** [comment]
\>all these complains about the new layout
![kujouriu-3](https://user-images.githubusercontent.com/67625878/118581886-ffeb0f00-b7c4-11eb-9ef8-c422c1b4bd01.png)

**Comment by Furitenman** [comment]
We should make the loli of the week bigger to even all out.

**Comment by sharmayu** [comment]
![1621309321580](https://user-images.githubusercontent.com/67625878/118599029-844b8b00-b7e1-11eb-8b38-e3f1c2edb071.png)
This looks nice can this be done? Or at least just the grid format? Close if it's too bothersome, I'm already satisfied with what we have...

**Comment by watterle** [comment]
imagine listening to the thread

**Comment by sharmayu** [comment]
only to the good ideas, since that format makes it look like a newspaper and i like newspapers

**Comment by Furitenman** [comment]
It looks cramped as fuck.

**Comment by sharmayu** [comment]
yeah, looking at it now it's probably gonna cramp the where to play section. i guess what we have is good enough, until we find a better layout

**Comment by riichinomics** [comment]
Can't believe you've donned this.

**Comment by sharmayu** [comment]
shut the fuck up this layout is perfect

**Comment by watterle** [comment]
oh no...

**Comment by sharmayu** [comment]
there's nothing wrong with it i swear the people complaining are all retarded idiots with ZERO (0) sense of what TRUE and SENSIBLE web design is. There's a sidebar for the updates, and it doesn't feel cramped. The loli and the tourney info looks snug, like a mother and her lewd daughter on an afternoon trip to shop for ingredients for dinner.

**Comment by Furitenman** [comment]
We can just change it again. It's been what, two weeks?

**Comment by sharmayu** [comment]
What's the hot new web design meme? 3d transitions?

**Comment by sharmayu** [comment]
minimalism

**Comment by Furitenman** [comment]
What about some postmodern australianism?
![](https://user-images.githubusercontent.com/82289213/119356328-97110480-bca6-11eb-84b3-2a6ba41a6a5d.png)

**Comment by watterle** [comment]
https://boards.4channel.org/g/thread/81728323#p81756161
I asked the experts

**Comment by sharmayu** [comment]
>What about some postmodern australianism?

it's hard to read for everyone but aussies, and fuck aussies. maybe on february 29 or something
Here's my minimalism proposal
![new repo proposal](https://user-images.githubusercontent.com/67625878/119357261-f1778880-bcd9-11eb-837f-d9e94a9bfcce.png)

**Comment by Furitenman** [comment]
Looks nice but it lacks lolis. Unless we do an animated loli background. Someone has some good loli hentai we can add as animated background?

**Comment by sharmayu** [comment]
i don't have any lewd loli saved, but here's another one. well, it's easy to change the background. we're also following the hot new meme with anime girls as background images
![new repo proposal 2](https://user-images.githubusercontent.com/67625878/119358114-e2450a80-bcda-11eb-9e82-6686e55057e1.png)

**Comment by Furitenman** [comment]
Sounds good, Get me the HD image and I'll start working on it.

**Comment by sharmayu** [comment]
https://files.catbox.moe/6n4x8n.jpg

**Comment by sharmayu** [comment]
There's a problem with that design. The updates, tourneys and loli of the week. Don't conveniently forget this.

**Comment by Furitenman** [comment]
I'll think of something

**Comment by watterle** [comment]
/g/ also suggests cerebral integration

**Comment by sharmayu** [comment]
![new repo proposal 3](https://user-images.githubusercontent.com/67625878/119359552-57650f80-bcdc-11eb-8131-9181d1ccd466.png)
here, what about this. the loli of the week can be the wallpaper. We're already using cerebral integration. we see loli, we feel happy.

**Comment by Furitenman** [comment]
It needs to be a HD image otherwise it'll look like shit, but we can always do that.

**Comment by sharmayu** [comment]
we can always run it through waifu2x if needed

**Comment by watterle** [comment]
does it really work that well? I never used it

**Comment by sharmayu** [comment]
it works well for me. i enhance my vn screenshots to be super HD with it, and they look fine.

**Comment by Furitenman** [comment]
It's still a work in progress
![](https://user-images.githubusercontent.com/82289213/119384819-8b810600-bcc5-11eb-81a6-9a02cbc69a8d.png)

**Comment by sharmayu** [comment]
hmmm maybe the position of the banner and the title can be changed. and there should be a bit more spacing beneath "play now." and maybe change play now to start game?

**Comment by Furitenman** [comment]
I'll see what I can do when I get home.

**Comment by Furitenman** [comment]
@sharmayu @watterle What about this?
![](https://user-images.githubusercontent.com/82289213/119533972-b1221400-bd86-11eb-9acf-98ecf926751c.png)

**Comment by Furitenman** [comment]
btw yes there will be a fucking light theme.

**Comment by watterle** [comment]
dark = trash, simple as that

**Comment by Furitenman** [comment]
Deluded

**Comment by sharmayu** [comment]
lightards are retarded and they're legally blind, what's new?
also, we need a way to utilize that space. sooner or later i'm gonna go crying on how that news and updates section is too cramped, just watch

**Comment by sharmayu** [comment]
![119533972-b1221400-bd86-11eb-9acf-98ecf926751c](https://user-images.githubusercontent.com/67625878/119576068-a305df00-bdea-11eb-97d3-7b875424ffbb.png)
Here's a suggestion

**Comment by sharmayu** [comment]
c-can we have option for classic as well? i (and my friend(s)) actually use the quick links below...

**Comment by sharmayu** [comment]
unless we can put the quick links on the picture then it's good

**Comment by Furitenman** [comment]
I’ll see what I can do

**Comment by Furitenman** [comment]
I'm almost there. I'll see to add something for the quick links. The /mjg/ league stuff is not misaligned, but it moves because it gives it that 2000s aesthetic.
![](https://user-images.githubusercontent.com/82289213/119712026-75f41380-be60-11eb-8dd6-4266d7705545.png)

**Comment by sharmayu** [comment]
\>links move
\>you have to have 360noscope aim to click what you want

**Comment by Furitenman** [comment]
Okay, it's finished. Unless there's any other changes you want I'll push it.
![](https://user-images.githubusercontent.com/82289213/119859739-f163cc80-bf15-11eb-94c6-f4e479e480c2.png)
![](https://user-images.githubusercontent.com/82289213/119859764-f4f75380-bf15-11eb-8585-91ca7edb6f46.png)

**Comment by sharmayu** [comment]
For everything there is a new issue, a time for every activity in the repo A time to update and a time to ignore everything in the thread. A time to fold and a time to push new layouts for no reason at all. 

This is a time to push.

\>still no quicklinks
Okay...

**Comment by sharmayu** [comment]
<details>
  <summary>uhhhhh</summary>
we're getting the classic layout button, right......? or at least make it a different page..... my quicklinks...
</details>

**Comment by Furitenman** [comment]
`>He lacks the information`

**Comment by watterle** [comment]
![982](https://user-images.githubusercontent.com/49875739/119865488-ffb4e700-bf1b-11eb-9a4a-8396719e7330.png)

whitebros?

**Comment by sharmayu** [comment]
![1600288291811](https://user-images.githubusercontent.com/67625878/119865550-5cc99080-bf4e-11eb-9c3e-ac025dae72e8.png)
This is triggering my autism

**Comment by watterle** [comment]
also light theme is a bit too bright

**Comment by Furitenman** [comment]
Use the dark theme :^)

**Comment by sharmayu** [comment]
/>my bride meido i worked so hard for not anymore in the repo at all because i forgot
i knew this day would come, brb deleting the entire repo there's no point anymore

**Comment by Furitenman** [comment]
I mean, she's got tons of banners, but we can add her somewhere.

**Comment by Furitenman** [comment]
Important pages should be fixed now

**Comment by sharmayu** [comment]
what's the point it's all gonna be deleto now

**Comment by Furitenman** [comment]
Okay, everything important *should* work now. Please open new issues for other shit.

**Comment by Furitenman** [comment]
> 
> 
> For everything there is a new issue, a time for every activity in the repo A time to update and a time to ignore everything in the thread. A time to fold and a time to push new layouts for no reason at all.
> 
> This is a time to push.
> 
> >still no quicklinks
> Okay...

Can't believe I actually listened to you.
