### ISSUE TITLE
song

### ISSUE THREAD

**Issue by watterle** [vg-mjg/mjg-repo#88]
>remove pavarotti
>add something else
>it doesn't work

based

**Comment by Furitenman** [comment]
Based schizo issue

**Comment by sharmayu** [comment]
what the fuck's a pavarotti

**Comment by watterle** [comment]
a big guy https://www.youtube.com/watch?v=cWc7vYjgnTs

**Comment by sharmayu** [comment]
for me

**Comment by watterle** [comment]
literally me too
