### ISSUE TITLE
Guides theme

### ISSUE THREAD

**Issue by watterle** [vg-mjg/mjg-repo#89]
fuck darkfags, which css entry do I have to bother to fix this?
![939](https://user-images.githubusercontent.com/49875739/118858914-e982a780-b8d9-11eb-991e-64fd8fc5ad5e.png)

**Comment by Furitenman** [comment]
If it's an old page it might just need the .js files and theme switcher.

**Comment by Furitenman** [comment]
Well, no. I had to rewrite it. Should work now for your psychopath needs.
