### ISSUE TITLE
Better wording on "how to play video game mahjong"

### ISSUE THREAD

**Issue by Furitenman** [vg-mjg/mjg-repo#90]
From some anon:

>Yo.
>https://repo.riichi.moe/guides/how-to-play-video-game-mahjong.html
>There was a very amusing retard on /v/ who got confused by some of the wording I wrote in here awhile ago. Can I have someone change/add some lines?
>
>Specifically, under "Sets", can we add the line
>>In absolutely no case are you allowed to make runs out of the Dragons or Wind tiles. They can only ever be triplets, or your pair for the 4 sets and a pair.
>
>Then under Yaku, can we add to the end
>>You must STILL make 4 sets and a Pair to have your valid yaku. The ONLY exceptions to this are yakus called 7 pairs and 13 orphans.
>
>Finally, for the furiten section, can you erase that bit about stealing the copypasta from the thread? I think that joke has run it's course.
>
>Kthx I love u.

I might do it later. Just putting it here to remember ~(or if someone else wants to do it)~

**Comment by watterle** [comment]
but it's already done

**Comment by Furitenman** [comment]
My bad. The meds aren't working.

**Comment by sharmayu** [comment]
protip: if you take 2x more meds it becomes 2x more effective
