### ISSUE TITLE
RB1/RMS HTML version

### ISSUE THREAD

**Issue by sharmayu** [vg-mjg/mjg-repo#91]
An HTML version of RB1 and RMS, and maybe some of the good books. Last time I couldn't because I don't know how to use mahjong tiles fonts. I still don't know how, but I'll maybe someone else knows.
>But the RB1 VN...?

Maybe in a year or so because I can't write for shit

**Comment by watterle** [comment]
but why? PDF are good enough
and this guy has nice tiles https://natsuai.com/static/css/mahjong.css

**Comment by sharmayu** [comment]
if you want to direct people to certain articles, it would be helpful. i also don't know how to used that css

**Comment by Furitenman** [comment]
It's not a bad idea, *but* it is a hassle to pass a 300 pages or so book into .html. Easiest solution I could think of is take the raw files and see if there's a way to turn that into .html.

**Comment by watterle** [comment]
They are available as .tex files....
Shan't touch them

**Comment by sharmayu** [comment]
I can convert them through pandoc and manually edit in the tiles. I've tested it and it works okay, I just have to integrate the light/dark mode to it. I JUST HAVE TO FIGURE OUT HOW TO INPUT THE TILES TO HTML.

As for rms, we can just ask the guy who translated it for the raw files.

**Comment by sharmayu** [comment]
Alright, finally found out how to use the .css file. Working on it now

**Comment by sharmayu** [comment]
Can anyone check if they can see the tiles here?

https://repo.riichi.moe/books/rb1/ch3.html

**Comment by Furitenman** [comment]
Nope

**Comment by sharmayu** [comment]
I can't cope... can you send a screenshot of the top section?

**Comment by watterle** [comment]
can see the aka too

**Comment by Furitenman** [comment]
Can see it as well

**Comment by sharmayu** [comment]
only firefoxchads can see aka, everyone else can't. so in the html version i'll just indicate through text if the tile is aka or not.

**Comment by watterle** [comment]
doesn't everybody use firefox...?

**Comment by sharmayu** [comment]
> Can see it as well. Edit: They're a bit small, can you maybe make them bigger? If it's a font, should be a thing of applying font-size probably.

What about now? I've tried to make it 5.0em instead of the previous 2.6em. I'm still gonna work on this slowly, maybe when time allows it.
> doesn't everybody use firefox...?

I use Brave as a second browser, because sometimes I do feel like the chrome-variants runs smoother. But yeah, fuck chrometards.

**Comment by Furitenman** [comment]
Yeah, that looks much better. Maybe you can also read the book and kill two birds with one stone. That's what I did. I'll see if I can find a workaround for the aka tiles in .css that the authors don't know about.

**Comment by sharmayu** [comment]
>Maybe you can also read the book and kill two birds with one stone

oh shit, time to drop this project. shan't ever read.
... just kidding, i'll just edit the tiles while trying to avoid reading as much words as possible.
