### ISSUE TITLE
Meido sounds

### ISSUE THREAD

**Issue by watterle** [vg-mjg/mjg-repo#92]
Some people (me) hear them only when pressing on meido, others (@sharmayu) hear them when pressing every link. Others don't see meido at all. Mystery of webdev

**Comment by Furitenman** [comment]
>Hears meido all the time
Hmm I’m thinking schizo

**Comment by sharmayu** [comment]
no it's not schizo...

https://user-images.githubusercontent.com/67625878/119126629-d6044780-ba65-11eb-8cef-2a18db301f3f.mp4

**Comment by Furitenman** [comment]
The browser not playing sounds could be a cross-domain restriction, that disallows the file loading in the background. Your error is really odd. Can you tell me what browser and version are you using?

**Comment by sharmayu** [comment]
Firefox latest version
![1608194294930](https://user-images.githubusercontent.com/67625878/119132226-08657300-ba6d-11eb-824f-f6f92348ff3c.png)

Also tried it in brave, same sound issue.
![1605628107522](https://user-images.githubusercontent.com/67625878/119132255-12877180-ba6d-11eb-9c66-a905ee1747cf.png)

**Comment by sharmayu** [comment]
> 
> 
> Firefox latest version
> ![1608194294930](https://user-images.githubusercontent.com/67625878/119132226-08657300-ba6d-11eb-824f-f6f92348ff3c.png)
> 
> Also tried it in brave, same sound issue.
> ![1605628107522](https://user-images.githubusercontent.com/67625878/119132255-12877180-ba6d-11eb-9c66-a905ee1747cf.png)
> 
> Also OS is Windows Embedded 8.1, if it's somehow relevant
> ![1601123946370](https://user-images.githubusercontent.com/67625878/119132541-6b570a00-ba6d-11eb-8029-88be49173be4.png)

I always thought the sound was a feature, not a bug and greeting people with a noisy meido "PEI" was normal.

**Comment by watterle** [comment]
same firefox version as shar, windows 10, but it works as expected

**Comment by Furitenman** [comment]
I was only able to reproduce this error in Edge. I've tried Firefox, Chrome and Brave and no error. I think I know why, I'll push something and you can test it.

**Comment by sharmayu** [comment]
It's fixed now. Wow. I don't know about the rest tho.
