### ISSUE TITLE
Optimize search function

### ISSUE THREAD

**Issue by sharmayu** [vg-mjg/mjg-repo#93]
How do we do it?

**Comment by KioKenN** [comment]
We set up a treasure hunt so everyone get's familiar with the layout of the repo.

**Comment by sharmayu** [comment]
But how tho?

**Comment by watterle** [comment]
we make a prize, and hide the link somewhere in the repo

**Comment by sharmayu** [comment]
is the prize the famed akochan lewd dumps??

**Comment by Furitenman** [comment]
The prize is one akochan lewd. Don’t get them too greedy.

**Comment by watterle** [comment]
unironically sounds good

**Comment by sharmayu** [comment]
\>was asking for a way to change from freefind search to something that looks better
\>turns into a discussion of treasure hunt and akochan lewds
never change, you schizos
