### ISSUE TITLE
I can't take it anymore

### ISSUE THREAD

**Issue by sharmayu** [vg-mjg/mjg-repo#94]
It's so fucking shit I don't know why I even designed that. I'm reverting everything in 1-2 days.
![eb5a88d964984115b38bb1fee50b936b68557bbb35580af8db233237168f2ec4](https://user-images.githubusercontent.com/67625878/119914297-6ecd2280-bf92-11eb-911b-0c00db954e4f.jpg)

**Comment by sharmayu** [comment]
![mahjong](https://user-images.githubusercontent.com/67625878/119927787-b95b9880-bfac-11eb-860b-b7e262e8bed8.jpg)

**Comment by sharmayu** [comment]
nevermind, i'm working on fixing everything.

**Comment by sharmayu** [comment]
it is finished.

**Comment by Furitenman** [comment]
If I add support for the old design will you stop moaning?

**Comment by sharmayu** [comment]
i already reverted it back to the old design it's too late. well, you can add an option for the "new" one i guess

**Comment by Furitenman** [comment]
So you made me redesign the whole thing to your liking just to revert it the next day?

**Comment by sharmayu** [comment]
yeah sorry. alright i'm gonna write the repo guidelines and post it issues so these kinds of stuff won't happen again

**Comment by watterle** [comment]
that's why you shouldn't work for schizos
