### ISSUE TITLE
/mjg/ REPO CONSTITUTION

### ISSUE THREAD

**Issue by sharmayu** [vg-mjg/mjg-repo#95]
# /mjg/ REPO CONSTITUTION

We the repoanons of the /mjg/ repo, in order to form a more perfect website, establish timely updates, insure thread observation, provide for the common anon, promote mahjong and its clients, and secure the files we document to ourselves and our cloud storage, do ordain and establish this Constitution for the /mjg/ Repo.

# Article 0 - Original Principle
This mahjong repository of /mjg/, by /mjg/, for /mjg/, shall not perish from the internet.

# Article I - The Repoanons and his Rights 

## Section 1
All repoanons under the vg-mjg Organization shall be given the power to push content updates that either pertains to Mahjong, the threads or their own discretion.
## Section 2
Repoanons shall be composed of anons who have made github accounts and have made at least one good edit on the repo, peer reviewed by the present repoanons. After then shall they be vested all the rights and privileges that comes with being a repoanon.
## Section 3
Any update content pushed by repoanons is also subject to removal or revision by the other repoanons.
Any conflict of interest by two or more repoanons shall be decided in a mahjong friendly match, with south round and standard rules.
In case of a 1v1 situation, both repoanons must provide their own partner, whose total points shall be added together.
## Section 4
Repoanons shall not be paid any monetary amount whatsoever. 
Any monetary value gained through the repository, from bitcoin miners or advertisements, shall go into funding repo activities such as storage facilities and any and all that pertains to the repo.
## Section 5
Repoanons and the vg-mjg organization shall not be held accountable for any and all mental health issues that arise from managing and handling the repo.
## Section 6
Repoanons shall not be influenced by sources outside of the 4chan /mjg/ threads when performing his repo duties.

# Article II - The Layout of the Repo

## Section 1
The general layout of the index.html file, defined as the document that modifies the home page of the /mjg/ repo, shall not be infringed.
Small modifications to individual elements and quality-of-life enhancements shall be permitted, as long as it does not break the general aesthetic of the front page.
## Section 2
Individual pages to the repo, defined as html pages excluding the index, Library of Resources, Comics and OC and /mjg/ Tourneys,  shall be allowed to have different layouts to the discretion of the repoanon who posted it
## Section 3
The Loli of the Week shall be voted upon through an officially sanctioned poll, and its results must be honored for a week no matter the results.
Investigations on proxy voting are allowed to take place, given that there is sufficient evidence for it.
## Section 4
No explicit images can be posted anywhere in the index.html files. Suggestive ones are allowed, as long as any or all genitalia is hidden or covered and no sexual penetration of genitalia between two or more individuals is presented.
An exception is to be made of images of the yuri nature, as it is by definition a pure act of romance.
## Section 5
Autoplay sounds and links that lead to malicious sites are allowable, granted it is done in a comedic fashion. Its permanence shall be allowed to be put into debate by other repoanons, and shall be settled through the guidelines stated in Article I Section 3 of this Constitution.

# Article III - The Archival of Information

## Section 1
All resources, mods, OC, activity, and any sort of mahjong information posted in the thread or taken from outside sources, as long as it holds credibility, shall be compiled and archived in the repo. 
## Section 2
The repoanons must provide a secondary backup to all the files posted in the thread outside of the download link location the original post has been located at.
## Section 3
In the case of malicious mods and programs that overreach the functions stated by it, it must be either removed or its full functions and explanations on what it does must be written alongside it.
The lone exception to this rule is the Mahjong Soul Plus mod “Decency Patch,” which is in truth a nude mode for the lolis. This is a safety feature against people outside of the 4chan mahjong general threads.
## Section 4
Pertaining to the collection of information outside of mahjong, it shall be left to the discretion and responsibility of the individual repoanon.
## Section 5
The addition of mahjong-unrelated media to the repo is permitted, and it shall be left to the discretion and responsibility of the individual repoanon.

# Article IV - Additional Provisions

## Section 1
In the case of outside infringement by sources beyond the 4chan mahjong general, the repo shall be deleted and a backup of a repo integrity-checked by the thread shall be established.
## Section 2
In the case of the repo deleted by a rogue repoanon, a backup shall be established, and the repoanon shall still be allowed the right and privileges of a repoanon as stated in Article I.
## Section 3
In the case of repoanons splitting and establishing separate repositories, it shall be permitted and the links posted on the OP shall be fought upon by the two groups through shitposting and, if both parties are willing, a best of three friendly with the guidelines stated in Article I Section 3 of this Constitution.
## Section 4
Anons who have rightfully won a tournament are allowed to change and or add any element in the repo, granted it does not go against the rules stated in this constitution. 
In group tournaments and leagues, the winning team is only allowed one request. 

# Article V - Mascot of the Repo
## Section 1
Riu Kujou, maid of Chiori Mikami, shall be the undisputed mascot of the repo. As long as the repo still stands true to its original spirit, there shall be no objections about this.

# Article VI - Changes to the Constitution
## Section 1
No changes shall be made in this constitution, unless requested by a repoanon who has won a friendly match against dissidents to his changes within the guidelines stated in Article I Section 3 of this Constitution.

**Comment by sharmayu** [comment]
Open to Amendments.

**Comment by watterle** [comment]
Missing an article about changing the constitution

**Comment by watterle** [comment]
Missing an article about winning a tourney and getting a freebie change, unless it breaks a rule

**Comment by sharmayu** [comment]
updated

**Comment by watterle** [comment]
Original principle or something: mjg repo for /mjg/, from /mjg/, and by /mjg/ or something

**Comment by watterle** [comment]
after the remaks, before the article 1

**Comment by sharmayu** [comment]
what about now?

**Comment by watterle** [comment]
decent

**Comment by watterle** [comment]
missing an article about maido being the repo mascot

**Comment by sharmayu** [comment]
done all

**Comment by Furitenman** [comment]
Holy autism

**Comment by Furitenman** [comment]
The friendly rule should have an extra paragraph that 1v1 matches should be filled with bots to avoid shitters.

**Comment by watterle** [comment]
*tobi nashi

**Comment by Furitenman** [comment]
Friendlies suck for that. /mjg/ repo tourney doko?

**Comment by KioKenN** [comment]
![cry4help](https://user-images.githubusercontent.com/79859384/119974838-d9478800-bfbd-11eb-8671-00c7c633de0f.png)

**Comment by Furitenman** [comment]
Okay, sounds good. About the repo permissions I do not agree that anyone should get push permission. Everyone should start with PR to show their changes do not go against the rules or are simply shit. There should be a trial period at least.

**Comment by sharmayu** [comment]
that's true. but i think the permissions are being handled by @watterle  currently? i dunno what he's doing

**Comment by Furitenman** [comment]
The same thing he does with the league: rigging :^). It’s fine though, he’ll fix it later.

**Comment by watterle** [comment]
yeah it's redone, at the start you have only read permission

**Comment by sharmayu** [comment]
uhhh so what are the specifics on becoming official repoanon(tm)? i need to rewrite 1-2

**Comment by Furitenman** [comment]
Update the repo/add new (mahjong-related) content/help fixing the fucked up layout?

**Comment by watterle** [comment]
loli master or 500 confirmed commits

**Comment by watterle** [comment]
moved to https://github.com/vg-mjg/mjg-repo/blob/master/CONSTITUTION.md

**Comment by watterle** [comment]
this is more of a discussion

**Comment by watterle** [comment]
fuck the constitution

**Comment by Furitenman** [comment]
Oh no no no how will democracyfags ever recover???
