### ISSUE TITLE
Header has a 1 pixel difference between night mode and day mode

### ISSUE THREAD

**Issue by BUTCHDEADLIFT** [vg-mjg/mjg-repo#99]
Tbh I think the night mode being the same image but darker looks like shit too.

**Comment by Furitenman** [comment]
The entire repo is a botched patch up since they can’t into git. I’ll do a proper reverse to the push when I get home.

**Comment by sharmayu** [comment]
fine i'll change it back ;_;

**Comment by watterle** [comment]
don't touch my hat on light theme

**Comment by sharmayu** [comment]
well i brought back maid as well
